rustc --version#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────
#  deploy.sh — Build & deploy Soroban faucet to Stellar Testnet
# ────────────────────────────────────────────────────────────
set -euo pipefail

# ── Config ──────────────────────────────────────────────────
NETWORK="testnet"
RPC_URL="https://soroban-testnet.stellar.org"
PASSPHRASE="Test SDF Network ; September 2015"
FRIENDBOT="https://friendbot.stellar.org"
CONTRACT_DIR="contracts/faucet"
WASM_FILE="target/wasm32-unknown-unknown/release/faucet.wasm"

# Colours
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; NC='\033[0m'; BOLD='\033[1m'

log()  { echo -e "${CYAN}[deploy]${NC} $*"; }
ok()   { echo -e "${GREEN}[✓]${NC} $*"; }
warn() { echo -e "${YELLOW}[!]${NC} $*"; }
die()  { echo -e "${RED}[✗]${NC} $*"; exit 1; }

# ── Prerequisites ────────────────────────────────────────────
command -v soroban  >/dev/null 2>&1 || die "soroban CLI not found. Install: https://soroban.stellar.org/docs/getting-started/setup"
command -v cargo    >/dev/null 2>&1 || die "cargo not found. Install Rust: https://rustup.rs"

# ── Step 1: Generate / load deployer keypair ─────────────────
KEY_FILE=".stellar_deploy_key"
if [[ -f "$KEY_FILE" ]]; then
  log "Loading existing deploy key from $KEY_FILE"
  DEPLOYER_SECRET=$(cat "$KEY_FILE")
  DEPLOYER_PUBLIC=$(soroban keys public-key deployer-key 2>/dev/null || echo "")
else
  log "Generating new deployer keypair…"
  soroban keys generate deployer-key --network testnet 2>/dev/null || true
  DEPLOYER_SECRET=$(soroban keys show deployer-key)
  echo "$DEPLOYER_SECRET" > "$KEY_FILE"
  chmod 600 "$KEY_FILE"
  warn "Deploy key saved to $KEY_FILE — keep this secret!"
fi

DEPLOYER_PUBLIC=$(soroban keys address deployer-key)
log "Deployer public key: ${BOLD}$DEPLOYER_PUBLIC${NC}"

# ── Step 2: Fund with Friendbot ───────────────────────────────
log "Funding deployer account via Friendbot…"
FUND_RESP=$(curl -sf "$FRIENDBOT?addr=$DEPLOYER_PUBLIC" 2>&1 || true)
if echo "$FUND_RESP" | grep -q "400\|already funded\|Error"; then
  warn "Account may already be funded, continuing…"
else
  ok "Account funded via Friendbot"
fi

# ── Step 3: Build WASM ────────────────────────────────────────
log "Building Soroban contract (release)…"
cargo build \
  --manifest-path="$CONTRACT_DIR/Cargo.toml" \
  --target wasm32-unknown-unknown \
  --release \
  --quiet

ok "WASM built: $WASM_FILE"

# ── Step 4: Optimize WASM (if soroban optimize available) ─────
if soroban contract optimize --help >/dev/null 2>&1; then
  log "Optimizing WASM…"
  soroban contract optimize --wasm "$WASM_FILE" 2>/dev/null || true
  WASM_FILE="target/wasm32-unknown-unknown/release/faucet.optimized.wasm"
  [[ -f "$WASM_FILE" ]] && ok "Optimized WASM ready" || WASM_FILE="target/wasm32-unknown-unknown/release/faucet.wasm"
fi

# ── Step 5: Upload WASM to Testnet ────────────────────────────
log "Uploading WASM to Stellar Testnet…"
WASM_HASH=$(soroban contract install \
  --wasm "$WASM_FILE" \
  --source deployer-key \
  --network testnet \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$PASSPHRASE")

ok "WASM hash: ${BOLD}$WASM_HASH${NC}"

# ── Step 6: Deploy contract instance ─────────────────────────
log "Deploying contract instance…"
CONTRACT_ID=$(soroban contract deploy \
  --wasm-hash "$WASM_HASH" \
  --source deployer-key \
  --network testnet \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$PASSPHRASE")

ok "Contract deployed: ${BOLD}$CONTRACT_ID${NC}"

# ── Step 7: Initialize contract ───────────────────────────────
# Native XLM token on testnet
NATIVE_TOKEN="CDLZFC3SYJYDZT7K67VZ75HPJVIEUVNIXF47ZG2FB2RMQQVU2HHGCYW"
FAUCET_AMOUNT="100000000"  # 10 XLM in stroops
COOLDOWN="60"              # 60 seconds

log "Initializing contract…"
soroban contract invoke \
  --id "$CONTRACT_ID" \
  --source deployer-key \
  --network testnet \
  --rpc-url "$RPC_URL" \
  --network-passphrase "$PASSPHRASE" \
  -- initialize \
  --admin "$DEPLOYER_PUBLIC" \
  --faucet_amount "$FAUCET_AMOUNT" \
  --cooldown_seconds "$COOLDOWN"

ok "Contract initialized"

# ── Step 8: Fund the faucet contract ─────────────────────────
log "Sending 1000 XLM to faucet contract from Friendbot…"
FUND_FAUCET=$(curl -sf "$FRIENDBOT?addr=$CONTRACT_ID" 2>&1 || true)
ok "Faucet funded"

# ── Step 9: Write .env for frontend ──────────────────────────
ENV_FILE="frontend/.env.local"
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy.sh — $(date -u)
NEXT_PUBLIC_STELLAR_NETWORK=testnet
NEXT_PUBLIC_STELLAR_RPC_URL=$RPC_URL
NEXT_PUBLIC_NETWORK_PASSPHRASE=$PASSPHRASE
NEXT_PUBLIC_FAUCET_CONTRACT_ID=$CONTRACT_ID
NEXT_PUBLIC_NATIVE_TOKEN_ID=$NATIVE_TOKEN
NEXT_PUBLIC_FRIENDBOT_URL=$FRIENDBOT
EOF
ok "Frontend .env.local written"

# ── Step 10: Summary ─────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════${NC}"
echo -e "${BOLD}${GREEN}  Deployment Complete!                      ${NC}"
echo -e "${BOLD}${GREEN}═══════════════════════════════════════════${NC}"
echo -e "  Contract ID:    ${CYAN}$CONTRACT_ID${NC}"
echo -e "  WASM Hash:      ${CYAN}$WASM_HASH${NC}"
echo -e "  Deployer:       ${CYAN}$DEPLOYER_PUBLIC${NC}"
echo -e "  Explorer:       ${CYAN}https://stellar.expert/explorer/testnet/contract/$CONTRACT_ID${NC}"
echo ""
echo -e "  Next steps:"
echo -e "  1. cd frontend && npm install && npm run dev"
echo -e "  2. Open http://localhost:3000"
echo -e "  3. Connect Freighter wallet (testnet mode)"
echo ""
